export const UPDATE_NEWEST_PAGE = 'newest/UPDATE_NEWEST_PAGE'
export const UPDATE_NEWEST_CATEGORY = 'newest/UPDATE_NEWEST_CATEGORY'
export const REQUEST_NEWEST_VIDEOS = 'newest/REQUEST_NEWEST_VIDEOS'
export const RECEIVE_NEWEST_VIDEOS = 'newest/RECEIVE_NEWEST_VIDEOS'

export const REQUEST_BEST_VIDEOS = 'best/REQUEST_BEST_VIDEOS'
export const RECEIVE_BEST_VIDEOS = 'best/RECEIVE_BEST_VIDEOS'

export const REQUEST_FANCAM_VIDEOS = 'fanCam/REQUEST_FANCAM_VIDEOS'
export const RECEIVE_FANCAM_VIDEOS = 'fanCam/RECEIVE_FANCAM_VIDEOS'

export const REQUEST_IDOLS = 'idolList/REQUEST_IDOLS'
export const RECEIVE_IDOLS = 'idolList/RECEIVE_IDOLS'

export const REQUEST_IDOL = 'idolDetail/REQUEST_IDOL'
export const RECEIVE_IDOL = 'idolDteail/RECEIVE_IDOL'

export const REQUEST_IDOL_VIDEOS = 'idolVideoList/REQUEST_IDOL_VIDEOS'
export const RECEIVE_IDOL_VIDEOS = 'idolVideoList/RECEIVE_IDOL_VIDEOS'

export const REQUEST_IDOL_KARAOKES = 'idolKaraokeList/REQUEST_IDOL_KARAOKES'
export const RECEIVE_IDOL_KARAOKES = 'idolKaraokeList/RECEIVE_IDOL_KARAOKES'
