export const REQUEST_VIDEO_NEWEWST = 'videoNewest/REQUEST_VIDEO_NEWEWST'
export const RECEIVE_VIDEO_NEWEWST = 'videoNewest/RECEIVE_VIDEO_NEWEWST'

export const REQUEST_VIDEO_BEST = 'videoBest/REQUEST_VIDEO_BEST'
export const RECEIVE_VIDEO_BEST = 'videoBest/RECEIVE_VIDEO_BEST'

export const REQUEST_FANCAM_NEWEWST = 'fancamNewest/REQUEST_FANCAM_NEWEWST'
export const RECEIVE_FANCAM_NEWEWST = 'fancamNewest/RECEIVE_FANCAM_NEWEWST'

export const REQUEST_FANCAM_BEST = 'fancamBest/REQUEST_FANCAM_BEST'
export const RECEIVE_FANCAM_BEST = 'fancamBest/RECEIVE_FANCAM_BEST'

export const REQUEST_KARAOKE_NEWEWST = 'karaokeNewest/REQUEST_KARAOKE_NEWEWST'
export const RECEIVE_KARAOKE_NEWEWST = 'karaokeNewest/RECEIVE_KARAOKE_NEWEWST'

export const REQUEST_KARAOKE_BEST = 'karaokeBest/REQUEST_KARAOKE_BEST'
export const RECEIVE_KARAOKE_BEST = 'karaokeBest/RECEIVE_KARAOKE_BEST'

export const REQUEST_IDOL_LIST = 'idolList/REQUEST_IDOL_LIST'
export const RECEIVE_IDOL_LIST = 'idolList/RECEIVE_IDOL_LIST'

export const NEXT_PAGE_IDOL_NEWEWST = 'karaokeNewest/NEXT_PAGE_IDOL_NEWEWST'
export const PREV_PAGE_IDOL_NEWEWST = 'karaokeNewest/PREV_PAGE_IDOL_NEWEWST'
export const REQUEST_IDOL_NEWEWST = 'karaokeNewest/REQUEST_IDOL_NEWEWST'
export const RECEIVE_IDOL_NEWEWST = 'karaokeNewest/RECEIVE_IDOL_NEWEWST'

export const NEXT_PAGE_IDOL_BEST = 'karaokeBest/NEXT_PAGE_IDOL_BEST'
export const PREV_PAGE_IDOL_BEST = 'karaokeBest/PREV_PAGE_IDOL_BEST'
export const REQUEST_IDOL_BEST = 'karaokeBest/REQUEST_IDOL_BEST'
export const RECEIVE_IDOL_BEST = 'karaokeBest/RECEIVE_IDOL_BEST'
